name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r . ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }}:/home/ec2-user/app

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} << 'EOF'
          cd /home/ec2-user/app
          docker build -t attendance_app .
          docker stop attendance_app || true
          docker rm attendance_app || true
          docker run -d --name attendance_app -p 80:80 attendance_app
        EOF
