name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Create remote directory
      run: |
        echo "Creating remote directory"
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} "mkdir -p /home/${{ secrets.USER_NAME }}/app"

    - name: Copy files to EC2
      run: |
        echo "Copying files to EC2"
        scp -v -o StrictHostKeyChecking=no -r * ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }}:/home/${{ secrets.USER_NAME }}/app

    - name: Install Docker on EC2
      run: |
        echo "Installing Docker"
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} << 'EOF'
          sudo yum update -y
          sudo amazon-linux-extras install docker
          sudo service docker start
          sudo usermod -a -G docker ${{ secrets.USER_NAME }}
        EOF

    - name: Deploy application
      run: |
        echo "Deploying application"
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} << 'EOF'
          cd /home/${{ secrets.USER_NAME }}/app
          docker build -t attendance_app .
          docker stop attendance_app || true
          docker rm attendance_app || true
          docker run -d --name attendance_app -p 80:80 attendance_app
        EOF
