name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Create remote directory
      run: |
        echo "Creating remote directory"
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} "mkdir -p /home/${{ secrets.USER_NAME }}/app"

    - name: Copy files to EC2
      run: |
        echo "Copying files to EC2"
        scp -r -o StrictHostKeyChecking=no ./* ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }}:/home/${{ secrets.USER_NAME }}/app

    - name: Check remote directory contents
      run: |
        echo "Checking remote directory contents"
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} "ls -la /home/${{ secrets.USER_NAME }}/app/backend"

    - name: Deploy application
      run: |
        echo "Deploying application"
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} << 'EOF'
          export MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          export MYSQL_USER=${{ secrets.MYSQL_USER }}
          export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          export MYSQL_DB=${{ secrets.MYSQL_DB }}
          cd /home/${{ secrets.USER_NAME }}/app/backend
          ls -la
          docker-compose up -d --build
        EOF
